### PR TITLE
update special pages example to new baseline

### PR DESCRIPTION
**Pull request by shakyShane**
This change pulls the baseline we used for onboarding into the example

- localisation
- environment overrides
- default messaging (initial setup, exceptions etc)
- safe initialization with error reporting
- schema-based boundary definitions

### CODE REVIEW

**Comment by shakyShane** [comment]
* **#994** <a href="https://app.graphite.dev/github/pr/duckduckgo/content-scope-scripts/994?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shakyShane and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by mgurgel — APPROVED** [review]
🚢

**Comment by GioSensation** [comment]
This is awesome. Thanks for doing this, @shakyShane ! Is there already a paragraph in the README that explains how to start a new special page? If not, it may be worth adding it. If the steps are more than a "Right click → duplicate folder", you can consider adding an npm script that guides people with prompts, but that's probably overkill. Up to you. Great job here 🚀.

**Comment by shakyShane** [comment]
@GioSensation yeah, I'm going to flesh out the docs this week, both in the repo and something in Asana too :)

**Pull request merged**
